---
title: "StormDataAnalysis"
author: "Heli Pykälä"
date: "2016-04-28"
output: html_document
---

Data download and unzipping for reference
```{r}
#library(R.utils)
#dir.create("data")
#download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2", 
#              destfile = "data/StormData.csv.bz2", mode = "wb")
#bunzip2("data/StormData.csv.bz2")
```

Read data and select only interesting columns for the analyisis. Empty string is null.
```{r}
library(data.table)
storm <- fread("data/StormData.csv", 
               select = c("BGN_DATE","STATE", "EVTYPE", "FATALITIES", "INJURIES", "PROPDMG", "PROPDMGEXP",
                          "CROPDMG", "CROPDMGEXP", "REFNUM"),
               na.strings = "",
               stringsAsFactors = TRUE)

```

Transformations
```{r}
storm[,BGN_DATE:=as.Date(BGN_DATE, format = "%m/%d/%Y") ]
```

```{r}
convertDamage <- function(dmgexp,dmg) {
    mult <- switch(toupper(dmgexp),
           "K" = 1E3,
           "M" = 1E6,
           "B" = 1E9,
           "1" = 1E1,
           "2" = 1E2,
           "3" = 1E3,
           "4" = 1E4,
           "5" = 1E5,
           "6" = 1E6,
           "7" = 1E7,
           "8" = 1E8,
           1)
    mult*dmg
}

storm[,CDMG:=mapply(convertDamage,.SD[,CROPDMGEXP],.SD[,CROPDMG])]
storm[,PDMG:=mapply(convertDamage,.SD[,PROPDMGEXP],.SD[,PROPDMG])]
    
```

```{r}
head(storm[order(PDMG,decreasing = TRUE),])

```




```{r}
sum <- storm[,j=list(inj=sum(INJURIES), fat=sum(FATALITIES), pdmg = sum(PDMG), cdmg= sum(CDMG)), by=EVTYPE]
```



